### PR TITLE
Basilisk V3 Pro (Wired & Wireless) support

### PR DESCRIPTION
**Pull request by jakkornat**
# Basilisk V3 Pro (Wired ⚡️ & Wireless 🛰️) support

This change includes support for both wired and wireless Basilisk V3 Pro mouse 🐁. 

### Tested for: 
* Editing scroll static, wave, and spectrum lights 🌈.
* Editing logo static, wave, and spectrum lights 🌈.
* Editing side static, wave, and spectrum lights 🌈.
* Editing DPI 🏃🏻‍♀️ 
* Show battery level (when plugged only) ⚡️.

Thank you to 1kc for macOS gamers world a better place 🕹️

#### Note
Follow the UI PR [here](https://github.com/1kc/razer-macos/pull/818).

### CODE REVIEW

**Comment by jakkornat** [comment]
@1kc / @edualm are you able to check? ☺️

**Comment by nikhilsharma81181** [comment]
@edualm @jakkornat @dhobi @ineffyble @Theorian 

Please merge this if everything is working fine, I am eagerly waiting for v3 pro support 
And you I can help in terms of Flutter, Node.JS or AWS let me know 
Thanks

**Review by nikhilsharma81181 — APPROVED** [review]

**Review by nikhilsharma81181 — APPROVED** [review]

**Comment by nikhilsharma81181** [comment]
@edualm @jakkornat How I can make the build or install it on my mac ??

**Comment by nikhilsharma81181** [comment]
@edualm I wanted to run and contribute to fix bugs and enhance the code, Just wanted to help in free time after my current work, Thanks

**Comment by analystck** [comment]
Guys, I'm completely lost here, barely figured out how to leave comments. I see a branch with an update for V3 PRO, which is currently not supported. Can you please advise if there's a way to integrate these additions into the main release on my own? Or should I wait for an update? What's the usual timeline for this kind of thing?

**Comment by sergeyustyak** [comment]
> Guys, I'm completely lost here, barely figured out how to leave comments. I see a branch with an update for V3 PRO, which is currently not supported. Can you please advise if there's a way to integrate these additions into the main release on my own? Or should I wait for an update? What's the usual timeline for this kind of thing? Thanks in advance!!

https://github.com/1kc/razer-macos/issues/778#issuecomment-1579648255

**Pull request merged**
