### PR TITLE
Support for New DeathAdder Essential

### PR DESCRIPTION
**Pull request by WrathofthePast**

### CODE REVIEW

**Comment by WrathofthePast** [comment]
Confirmed Working in 1kc/razer-macos#477

**Comment by dhobi** [comment]
Thanks for the PR! 2 things which I want to address:
1. the PR contains some experimental/wip commits (adding a lot of code and remove it again later). While this does not seem to be a problem in terms of functionality, it can make it harder to read the git history.
2. it seems to me that you added functionality for two products at the same time. Again, not really an "issue" but I would prefer a PR for each product.

So in the end: Would it be possible for you to have 2 PR's (one for each product) and without the WIP commits?

**Comment by WrathofthePast** [comment]
> Thanks for the PR! 2 things which I want to address:
> 
> 1. the PR contains some experimental/wip commits (adding a lot of code and remove it again later). While this does not seem to be a problem in terms of functionality, it can make it harder to read the git history.
> 2. it seems to me that you added functionality for two products at the same time. Again, not really an "issue" but I would prefer a PR for each product.
> 
> So in the end: Would it be possible for you to have 2 PR's (one for each product) and without the WIP commits?

Uh, what's the second device? I'm confused as I didn't add more than one & I didn't add any wip commits... I did add Huntsman V2 Analog support, but that was already merged here (still waiting to be merged on the razer-macos side though). I see that there's tons of commits. When I added Huntsman V2 Analog support, I got very confused on how PRs worked (apparently I needed the GitHub desktop app), so I ended up having tons of commits.

**Comment by WrathofthePast** [comment]
@dhobi, only the last 3 commits haven't been merged yet. All the prior ones listed got merged in #13.

**Comment by dhobi** [comment]
Aha yes, I see now. I guess you just continued working on your master branch and now created another PR from it?

My guess is that even if the commits are already in this repository (content wise) the commit hashes do not match and are therefore shown again as new. I believe that this is a side effect of "merging" from a fork (different repository). Seems to me as those fork merges behaves more like single cherry picks than a (same repository) merge.

What I would do:
1. "git reset" (not hard to not lose your changes!) to the commit where you started to work on the Deathadder => if done correctly, you should then have all the changes you did for this product in an uncommitted state.
2. "git stash" those changes away
3. git reset (hard!) your local master branch to the remote 1kc/librazermacos master
4. git stash pop the changes from before
5. git commit and push. You will have to use "force" push as the history on your repository has to be forcefully overwritten

Makes sense?

**Comment by WrathofthePast** [comment]
@dhobi, well it didn't work, but it did allow my PR in razer-macos to show the libmacosrazer submodule updates, so that's at least progress. Something still pretty screwed up though. When I tried the hard reset, I got an error. What's the syntax to do that?

**Comment by WrathofthePast** [comment]
@dhobi, I think I got it. How does it look now?

**Comment by dhobi** [comment]
@WrathofthePast LGTM now!

**Comment by WrathofthePast** [comment]
@dhobi, should I do the same for razer-macos? The DeathAdder Essential PR has my Huntsman V2 Analog PR included in it. The difference is my Huntsman V2 Analog PR hasn't been merged yet.

**Comment by WrathofthePast** [comment]
@dhobi, I did the same for the razer-macos PR & 1kc is happy. Thanks for the help!

**Comment by WrathofthePast** [comment]
@1kc, this PR still needs to be merged for New DeathAdder Essential support as the Razer-MacOS PR does not add it to librazermacos.

**Comment by 1kc** [comment]
ty will release now

**Pull request merged**
