### PR TITLE
Adding support for Razer BlackWidow V3 Pro

### PR DESCRIPTION
**Pull request by ryan-idea42**
Based my changes off of this Merge Request in OpenRazer project: https://github.com/openrazer/openrazer/pull/1514/files

Will do testing on my own keyboard in all 3 supported modes to see if everything works as appropriate as it would seem in the openrazer pull request.

### CODE REVIEW

**Comment by ryan-idea42** [comment]
As mentioned, tested this with the wired connection, and it works as expected. Bluetooth and Wireless mode, though, those won't be coming in through the USB interface, so probably not something this library can support. 

@1kc please advise. :-)

**Comment by 1kc** [comment]
Awesome! Might need to add changes to the frontend (https://github.com/1kc/razer-macos) as well, if you are planning on using it regularly. :)

**Comment by ryan-idea42** [comment]
@1kc Do you know if this library can support the Wireless or Bluetooth interfaces from Razer products? I don't see where it does in the code. From everything I see, it's USB interface only.

**Comment by 1kc** [comment]
> @1kc Do you know if this library can support the Wireless or Bluetooth interfaces from Razer products? I don't see where it does in the code. From everything I see, it's USB interface only.

I think there was one instance in the past where a 2.4G wireless mouse worked with this driver, in which the commands were sent through the dongle. Certainly not Bluetooth though. I imagine implementing Bluetooth would require digging around with the hardware, Bluetooth packet capturing etc?

**Comment by ryan-idea42** [comment]
> > @1kc Do you know if this library can support the Wireless or Bluetooth interfaces from Razer products? I don't see where it does in the code. From everything I see, it's USB interface only.
> 
> I think there was one instance in the past where a 2.4G wireless mouse worked with this driver, in which the commands were sent through the dongle. Certainly not Bluetooth though. I imagine implementing Bluetooth would require digging around with the hardware, Bluetooth packet capturing etc?

Yeah, I think you'd have to have something to capture the BT devices to get that working. In my case, it's wired in to a hub by my monitor... The person on the other frontend project that was wanting this was requesting for the wired, which can't be done with the current code base. 

You think I should remove the non-wired device types from this, then we can get this merged in? I have the changes ready in the front-end to support the keyboard in wired mode. :-)

**Comment by 1kc** [comment]
Yeah I think it's a good idea to remove the non-wired device types, otherwise people could get confused in the future. 😆

**Comment by ryan-idea42** [comment]
@1kc I think we're good to go now. Once this is merged into master, I'll send up a merge request for the frontend project.

**Pull request merged**
